[package]
name = "fzopnr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
skim = "0.9.4"
toml = "0.9.11"
webbrowser = "1.0.6"
